apiVersion: v1
kind: Service
metadata:
  name: bluegreen-frontend
  labels:
    name: bluegreen-frontend
spec:
  selector:
    app: frontend-blue
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 80

# apiVersion: v1
# kind: Service
# metadata:
#   name: static-site-service
#   labels:
#     app: static-site
#   annotations:
#     service.beta.kubernetes.io/linode-loadbalancer-throttle: '4'
# spec:
#   selector:
#     app: static-site
#   sessionAffinity: None
#   type: LoadBalancer
#   ports:
#     - name: http
#       port: 3000
#       protocol: TCP
#       targetPort: 80
